name: pyradio
version: '1.3.2'
summary: Command line internet radio player.
description: |
  Command line internet radio player.

grade: stable
confinement: strict

apps:
  pyradio:
    command: pyradio
    plugs: [network, pulseaudio, x11]
    environment:
       LC_ALL: C.UTF-8

parts:
  pyradio:
    source: https://github.com/coderholic/pyradio.git
    plugin: python
    stage-packages:
        - mplayer
        - vlc
        - libpulse0
