name: my-snap-name # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

confinement: devmode # use 'strict' once you have the right plugs and slots
grade: devel
icon: snap/gui/icon.png

apps:
  my-app:
    command: my-app
    desktop: share/applications/my-app.desktop
    #plugs:
    #- desktop
    #- desktop-legacy
    #- x11
    #- unity7

    #slots:

parts:
  # Patches to fix other parts
  patches:
    source: snap/patches
    source-type: local
    plugin: dump

    # DISABLED: Bug #1775582 “`organize:{ /: another-dir/ }` causes the items under host root directory to be copied in another-dir” : Bugs : Snapcraft
    # https://forum.snapcraft.io/t/organize-another-dir-causes-the-items-under-host-root-directory-to-be-copied-in-another-dir/5806
    #organize:
        #/: patches/
    override-build: |
      set -eu

      snapcraftctl build

      mkdir \
        --parents \
        "$SNAPCRAFT_PART_INSTALL"/patches
      mv \
        "$SNAPCRAFT_PART_INSTALL"/*.diff \
        "$SNAPCRAFT_PART_INSTALL"/*.patch \
        "$SNAPCRAFT_PART_INSTALL"/*.sed \
        "$SNAPCRAFT_PART_INSTALL"/patches \
        || true # Empty patches folder is allowed
    stage:
    - patches/*
    override-prime: 'true'

  my-app:
    after:
    - patches

    # See 'snapcraft plugins'
    plugin: nil

    override-stage: |
      set -eu

      snapcraftctl stage

      sed \
        --file "${SNAPCRAFT_STAGE}"/patches/patch-desktop-entries.sed \
        --in-place \
        "${SNAPCRAFT_STAGE}"/share/applications/*.desktop
